version: "3"
services:
  app:
    build: .
    ports:
      - "3500:3500"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
